package ExceptionHandeling;

public class FinallyBlock {

	
	// 
	public static void main(String[] args) 
	{
	
		
		try
		{
			int num=121/0;  
			System.out.println(num);
			
		}
		catch(ArithmeticException e)
		{
			
		}
		finally
		{
			
		}
		
		
		

	}

}
