package ExceptionHandeling;

public class FinallyWithReturn {

	public static void main(String[] args) 
	{
		
		System.out.println();
		

		
		
	}
	
	
	public static int returnData()
	{
		
		try
		{
			System.out.println("catch block");
			return 12;
		}
		finally
		{
			
		}
	}

}
